# Generated by Django 6.0.3 on 2026-03-26 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_object_id', models.CharField(max_length=100, unique=True, verbose_name='ID объекта')),
                ('object_name', models.CharField(max_length=255, verbose_name='Название объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=255)),
                ('ticket_text', models.TextField()),
                ('visitor_ext_id', models.CharField(blank=True, max_length=100, verbose_name='ID посетителя из ServiceBook')),
                ('visitor_name', models.CharField(max_length=200, verbose_name='ФИО посетителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.category', verbose_name='Категория')),
                ('id_employee_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='accounts.employee', verbose_name='Назначенный сотрудник')),
                ('id_employee_edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_tickets', to='accounts.employee', verbose_name='Последний редактировавший')),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.object', verbose_name='Объект')),
                ('id_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tickets.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='tickets/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Фото заявки',
                'verbose_name_plural': 'Фото заявок',
            },
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tag')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Связь заявки и тега',
                'verbose_name_plural': 'Связи заявок и тегов',
                'unique_together': {('id_ticket', 'id_tag')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, through='tickets.TicketTag', to='tickets.tag'),
        ),
    ]
